---
- name: Generate HAProxy Configuration
  template:
    src: haproxy.cfg.j2
    dest: /tmp/haproxy.cfg
    owner: root
    group: root
    mode: 0644
      
- name: Inject Generated HAProxy Configuration
  shell: cat /tmp/haproxy.cfg >> /etc/haproxy/haproxy.cfg
  args:
    warn: false

- name: Clean-up Generated Script For HAProxy Configuration
  file:
    path: /tmp/haproxy.cfg
    state: absent
