---
- name: Uninstall Galera Client Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    autoremove: yes
    autoclean: yes
    purge: yes
    state: absent
  with_items:
    - mysql-client

- name: Uninstall Galera Server Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    autoremove: yes
    autoclean: yes
    purge: yes
    state: absent
  with_items:
    - mysql-server
    - mysql-wsrep-{{ galera_major_version }}.{{ galera_minor_version }}
    - galera-3
  when:
    - inventory_hostname in groups['galera_node']

- name: Uninstall Galera Repository
  file:
    path: "/etc/apt/sources.list.d/galera.list"
    state: absent

- name: Uninstall Galera Keyring
  apt_key:
    id: '0xBC19DDBA'
    state: absent
