---
- name: Remove Galera Logs File
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/log/mysqld.log

- name: Remove Galera Run Directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/run/mysqld

- name: Remove Galera Databases Directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/mysql
  when:
    - not zfs_backend
