---
- name: Uninstall MariaDB Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    autoremove: yes
    autoclean: yes
    purge: yes
    state: absent
  with_items:
    - mariadb-server
    - mariadb-client

- name: Uninstall MariaDB Repository
  file:
    path: "/etc/apt/sources.list.d/mariadb-{{ galera_version_major }}.{{ galera_version_minor }}.list"
    state: absent

- name: Uninstall MariaDB Keyring
  apt_key:
    id: '0xF1656F24C74CD1D8'
    state: absent
