---
- name: Install Galera Keyring
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: '0xBC19DDBA'
    state: present

- name: Install Galera Repository
  template:
    src: galera.list.j2
    dest: "/etc/apt/sources.list.d/galera.list"
    owner: root
    group: root
    mode: 0644

- name: Install Galera Server Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    autoremove: yes
    autoclean: yes
    state: present
  with_items:
    - mysql-server
    - mysql-wsrep-{{ galera_major_version }}.{{ galera_minor_version }}
    - galera-3
  when:
    - inventory_hostname in groups['galera_node']

- name: Install Galera Client Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    autoremove: yes
    autoclean: yes
    state: present
  with_items:
    - mysql-client
