---
- name: Install MariaDB Keyring
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: '0xF1656F24C74CD1D8'
    state: present

- name: Install MariaDB Repository
  lineinfile:
    dest: "/etc/apt/sources.list.d/mariadb-{{ galera_version_major }}.{{ galera_version_minor }}.list"
    line: "deb [arch=amd64] http://kartolo.sby.datautama.net.id/mariadb/repo/{{ galera_version_major }}.{{ galera_version_minor }}/ubuntu {{ ansible_distribution_release }} main"
    create: yes
    state: present

- name: Install MariaDB Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    autoremove: yes
    autoclean: yes
    state: present
  with_items:
    - mariadb-server
    - mariadb-client
