---
- name: Create Galera Databases File
  shell: mysql_install_db --datadir=/var/lib/mysql --mysqld-file=$(which mysqld)
  args:
    warn: false

- name: Create Galera Databases Directory
  file:
    path: "{{ item }}"
    state: directory
    owner: mysql
    group: mysql
    recurse: true
  with_items:
    - /var/lib/mysql

- name: Create Galera Run Directory
  file:
    path: "{{ item }}"
    state: directory
    owner: mysql
    group: mysql
    recurse: true
  with_items:
    - /var/run/mysqld

- name: Create Galera Logs File
  file:
    path: "{{ item }}"
    state: touch
    owner: mysql
    group: mysql
  with_items:
    - /var/log/mysqld.log
