---
- name: Create Galera Group
  group:
    name: mysql
    system: yes
    state: present

- name: Create Galera User
  user:
    name: mysql
    group: mysql
    comment: MySQL Server
    home: /var/lib/mysql
    create_home: no
    system: yes
    state: present
