---
- name: Mount ZFS Dataset to Galera Directory
  mount:
    path: /var/lib/mysql
    src: "/dev/zvol/{{ zfs_pool_name }}/mysql"
    fstype: xfs
    opts: defaults
    passno: 2
    state: mounted

- name: Set Mounted ZFS Dataset Galera Directory Owner
  file:
    path: "{{ item }}"
    state: directory
    owner: mysql
    group: mysql
    recurse: true
  with_items:
    - /var/lib/mysql
