---
- name: Reload Galera Service
  systemd:
    daemon_reload: yes
  when:
    - service_init_status.stat.islnk is defined
    - service_init_status.stat.islnk

- name: Get Galera Service Info
  shell: service mysql status | grep not-found || true
  args:
    warn: false
  register: galera_service_info
  when:
    - service_init_status.stat.exists

- name: Enable Galera Service
  service:
    name: mysql
    enabled: yes
    state: restarted
  when:
    - galera_service_info.stdout.find("not-found") == -1
    - inventory_hostname != groups['galera_node'] | first

- name: Wait For Galera Service
  wait_for:
    port: 3306
    timeout: 15
    connect_timeout: 3
    delay: 5
    state: present
  when:
    - inventory_hostname != groups['galera_node'] | first
