---
- name: Generate MariaDB Tunning Configuration
  template:
    src: tunning.cnf.j2
    dest: /etc/mysql/conf.d/tunning.cnf
    owner: root
    group: root
    mode: 0644

- name: Generate MariaDB Galera Configuration
  template:
    src: galera.cnf.j2
    dest: /etc/mysql/conf.d/galera.cnf
    owner: root
    group: root
    mode: 0644
